input {
    file {
        path => "C:/Users/carlo/Documents/Meus arquivos/Faculdade/monitoramento-logging/logs/errors/error.log"
        start_position => "beginning"
        sincedb_path => "NUL"
        codec => json
    }
}
# filter {
    #   grok {
        #   match => { "message" => "%{TIMESTAMP_ISO8601:timestamp} %{LOGLEVEL:level} %{GREEDYDATA:message}" }
    #   }
#   }  
output {
    elasticsearch {
        hosts => ["http://localhost:9200"]
        index => "error-logs"
    }
    stdout {codec => rubydebug }
}